[package]
name = "brioche-pack"
version = "0.1.2"
edition = "2021"

[dependencies]
bincode = { version = "2.0.0-rc.3" }
bstr = { version = "1.8.0", features = ["serde"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_with = { version = "3.4.0" }
thiserror = "1.0.51"
tick-encoding = "0.1.2"
