[package]
name = "brioche-pack"
version = "0.1.3"
edition = "2021"

[dependencies]
bincode = { version = "2.0.0-rc.3" }
bstr = { version = "1.11.0", features = ["serde"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_with = { version = "3.11.0" }
thiserror = "2.0.3"
tick-encoding = "0.1.2"
